const products = [
    {
        id: '101',
        image: 'images/product-images/img1.webp',
        product_name: 'Aagyeyi Petite Kurtis',
        price: 305,
        discount: 18,
        rating: {
            stars: 4.2,
            reviews: 1800,
        },
        return_period: 8,
        delivery_date: '25 Nov 2023',
    },
    {
        id: '102',
        image: 'images/product-images/img2.webp',
        product_name: 'Designer Cloths Covers',
        price: 141,
        discount: 5,
        rating: {
            stars: 4,
            reviews: 78345,
        },
        return_period: 14,
        delivery_date: '25 Nov 2023',
        comapny: ' PANKHURI CREATION',
    },
    {
        id: '103',
        image: 'images/product-images/img3.webp',
        product_name: 'Fashionable Uniq Men Cap',
        price: 159,
        discount: 9,
        rating: {
            stars: 3.8,
            reviews: 458,
        },
        return_period: 4,
        delivery_date: '25 Nov 2023',
    },
    {
        id: '104',
        image: 'images/product-images/img4.webp',
        product_name: 'Fancy Lates Women Shirts',
        price: 264,
        discount: 0,
        rating: {
            stars: 3.9,
            reviews: 64820,
        },
        return_period: 10,
        delivery_date: '25 Nov 2023',
    },
    {
        id: '105',
        image: 'images/product-images/img5.webp',
        product_name: 'Stylish Man Caps',
        price: 157,
        discount: 7,
        rating: {
            stars: 4.8,
            reviews: 14532,
        },
        return_period: 5,
        delivery_date: '25 Nov 2023',
        comapny: 'AutoKraftz',
    },
    {
        id: '106',
        image: 'images/product-images/img6.webp',
        product_name: 'Tinkle Classy Kids Boys Kurtis',
        price: 239,
        discount: 9,
        rating: {
            stars: 4.1,
            reviews: 22576,
        },
        return_period: 4,
        delivery_date: '25 Nov 2023',
    },
    {
        id: '107',
        image: 'images/product-images/img7.webp',
        product_name: 'Comfy Modern Men Sweater',
        price: 416,
        discount: 20,
        rating: {
            stars: 3.9,
            reviews: 740,
        },
        return_period: 7,
        delivery_date: '25 Nov 2023',
    },
    {
        id: '108',
        image: 'images/product-images/img8.webp',
        product_name: 'Lasafiya Uniq Women Pants',
        price: 326,
        discount: 16,
        rating: {
            stars: 4,
            reviews: 32249,
        },
        return_period: 14,
        delivery_date: '25 Nov 2023',
    },
    {
        id: '109',
        image: 'images/product-images/img9.webp',
        product_name: 'Eybogler Mens Tshirt',
        price: 300,
        discount: 20,
        rating: {
            stars: 3.6,
            reviews: 28457,
        },
        return_period: 2,
        delivery_date: '25 Nov 2023',
    },
    {
        id: '110',
        image: 'images/product-images/img10.webp',
        product_name: 'Shimmering Glittering Jewellery',
        price: 167,
        discount: 7,
        rating: {
            stars: 3.9,
            reviews: 6002,
        },
        return_period: 12,
        delivery_date: '25 Nov 2023',
    },
    {
        id: '111',
        image: 'images/product-images/img11.webp',
        product_name: 'Gorgeous Wind Chimes',
        price: 126,
        discount: 16,
        rating: {
            stars: 4.2,
            reviews: 187,
        },
        return_period: 5,
        delivery_date: '25 Nov 2023',
    },
    {
        id: '112',
        image: 'images/product-images/img12.webp',
        product_name: 'Diwa Fancy Jewellery Sets',
        price: 228,
        discount: 28,
        rating: {
            stars: 4,
            reviews: 3458,
        },
        return_period: 8,
        delivery_date: '25 Nov 2023',
    },
    {
        id: '113',
        image: 'images/product-images/img13.webp',
        product_name: 'Attractive Dream Catcher',
        price: 198,
        discount: 8,
        rating: {
            stars: 4.2,
            reviews: 12598,
        },
        return_period: 7,
        delivery_date: '25 Nov 2023',
    },
    {
        id: '114',
        image: 'images/product-images/img14.webp',
        product_name: 'Attractive Watches',
        price: 99,
        discount: 9,
        rating: {
            stars: 3.5,
            reviews: 27550,
        },
        return_period: 6,
        delivery_date: '25 Nov 2023',
    },
    {
        id: '115',
        image: 'images/product-images/img15.webp',
        product_name: 'Princess Fusion Jewellery',
        price: 199,
        discount: 18,
        rating: {
            stars: 4.1,
            reviews: 3254,
        },
        return_period: 14,
        delivery_date: '25 Nov 2023',
    },
    {
        id: '116',
        image: 'images/product-images/img16.webp',
        product_name: 'Fancy Women Analog Watch',
        price: 160,
        discount: 10,
        rating: {
            stars: 4,
            reviews: 33248,
        },
        return_period: 3,
        delivery_date: '25 Nov 2023',
    },
    {
        id: '117',
        image: 'images/product-images/img17.webp',
        product_name: 'Stylish Graceful Mens Tshirt',
        price: 194,
        discount: 9,
        rating: {
            stars: 3.8,
            reviews: 15458,
        },
        return_period: 2,
        delivery_date: '25 Nov 2023',
    },
    {
        id: '118',
        image: 'images/product-images/img18.webp',
        product_name: 'Womens Stylish Sarees',
        price: 305,
        discount: 9,
        rating: {
            stars: 4,
            reviews: 7395,
        },
        return_period: 14,
        delivery_date: '25 Nov 2023',
    },
    {
        id: '119',
        image: 'images/product-images/img19.webp',
        product_name: 'Urban Sensational Mens Tshirt',
        price: 294,
        discount: 14,
        rating: {
            stars: 3.8,
            reviews: 7854,
        },
        return_period: 8,
        delivery_date: '25 Nov 2023',
    },
    {
        id: '120',
        image: 'images/product-images/img20.webp',
        product_name: 'Attractive Oil Dispenser',
        price: 105,
        discount: 7,
        rating: {
            stars: 4,
            reviews: 7421,
        },
        return_period: 1,
        delivery_date: '25 Nov 2023',
    },
    {
        id: '121',
        image: 'images/product-images/img21.webp',
        product_name: 'Fashionable Mens Wallet ',
        price: 151,
        discount: 11,
        rating: {
            stars: 4,
            reviews: 2568,
        },
        return_period: 4,
        delivery_date: '25 Nov 2023',
    },
    {
        id: '122',
        image: 'images/product-images/img22.webp',
        product_name: 'Graceful Versatile Women Purse',
        price: 275,
        discount: 25,
        rating: {
            stars: 4.2,
            reviews: 5401,
        },
        return_period: 7,
        delivery_date: '25 Nov 2023',
    },
    {
        id: '123',
        image: 'images/product-images/img23.webp',
        product_name: 'Kashvi Sensational Sarees',
        price: 399,
        discount: 12,
        rating: {
            stars: 3.8,
            reviews: 1542,
        },
        return_period: 6,
        delivery_date: '25 Nov 2023',
    },
    {
        id: '124',
        image: 'images/product-images/img24.webp',
        product_name: 'ADZOY Tripod',
        price: 818,
        discount: 18,
        rating: {
            stars: 3.8,
            reviews: 5575,
        },
        return_period: 5,
        delivery_date: '25 Nov 2023',
    },
    {
        id: '125',
        image: 'images/product-images/img25.webp',
        product_name: 'Chitrarekha Pettis Kurtis',
        price: 275,
        discount: 10,
        rating: {
            stars: 4.1,
            reviews: 557,
        },
        return_period: 3,
        delivery_date: '25 Nov 2023',
    },
    {
        id: '126',
        image: 'images/product-images/img26.webp',
        product_name: 'Fancy Sensational Mens Shirt',
        price: 382,
        discount: 12,
        rating: {
            stars: 3.7,
            reviews: 254,
        },
        return_period: 10,
        delivery_date: '25 Nov 2023',
    },
    {
        id: '127',
        image: 'images/product-images/img27.webp',
        product_name: 'Princess Trendy Girls Top',
        price: 204,
        discount: 15,
        rating: {
            stars: 3.8,
            reviews: 145,
        },
        return_period: 2,
        delivery_date: '25 Nov 2023',
    },
    {
        id: '128',
        image: 'images/product-images/img28.webp',
        product_name: 'Fancy Modern Mens Belt',
        price: 272,
        discount: 12,
        rating: {
            stars: 3.7,
            reviews: 458,
        },
        return_period: 2,
        delivery_date: '25 Nov 2023',
    },
    {
        id: '129',
        image: 'images/product-images/img29.webp',
        product_name: 'Trendy PartyWear Womens Sweater',
        price: 342,
        discount: 8,
        rating: {
            stars: 4.2,
            reviews: 1254,
        },
        return_period: 5,
        delivery_date: '25 Nov 2023',
    },
    {
        id: '130',
        image: 'images/product-images/img30.webp',
        product_name: 'Latest Graceful Women Flipflop',
        price: 280,
        discount: 20,
        rating: {
            stars: 4,
            reviews: 2457,
        },
        return_period: 4,
        delivery_date: '25 Nov 2023',
    },
    {
        id: '131',
        image: 'images/product-images/img31.webp',
        product_name: 'Flawsome Fancy Girls Frocks',
        price: 385,
        discount: 25,
        rating: {
            stars: 4.2,
            reviews: 3564,
        },
        return_period: 1,
        delivery_date: '25 Nov 2023',
    },
    {
        id: '132',
        image: 'images/product-images/img32.webp',
        product_name: 'Trendy Mens Sneakers',
        price: 349,
        discount: 9,
        rating: {
            stars: 4.3,
            reviews: 2547,
        },
        return_period: 2,
        delivery_date: '25 Nov 2023',
    },
];